### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by carlylechia** [carlylechia/CATALOGUE#34]
In this initial step, my teammates and I set up the Kanban board which we used to distribute the tasks created from the project requirements.
- The link to our Github project is attached [here](https://github.com/carlylechia/CATALOGUE/projects/1).
- My team consists of three members, and the tasks were distributed as follows:

>> Team member #1: @carlylechia 

>> Team member #2: @nottherealalanturing 

>> Team member #3: @Ogaga01 

Thanks in advance for the review 😅

**Comment by OLIPLICHE** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Pull request messages are meaningful 👏

## Required Changes ♻️

- Please make sure that each card on the board has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work
- Please make sure to add `Team member #2` and `Team member #1` to other cards as you did with `Team member#3`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Omar-Muhamad** [comment]
# Approved ✔
### Hi Team,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by carlylechia** [comment]
Thank you @Omar-Muhamad
